AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/ClassLength:
  Max: 160
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Exclude:
    - "test/**/*"
    - "lib/fizzy/cli/**/*"
    - "lib/fizzy/cli.rb"
    - "lib/fizzy/client.rb"
    - "lib/fizzy/formatter.rb"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "test/**/*"
    - "lib/fizzy/cli/**/*"
    - "lib/fizzy/client.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/fizzy/cli/**/*"
    - "lib/fizzy/client.rb"
    - "lib/fizzy/auth.rb"
    - "lib/fizzy/formatter.rb"

Metrics/PerceivedComplexity:
  Exclude:
    - "lib/fizzy/cli/**/*"

Naming/VariableNumber:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - "test/**/*"
